abbr -a -- aurc 'paru -G'
abbr -a -- auro 'paru -Qua'
abbr -a -- cdb 'cd ~/books'
abbr -a -- cdc 'cd ~/code'
abbr -a -- cdd 'cd ~/downloads'
abbr -a -- cdm 'cd ~/music'
abbr -a -- cdma 'cd ~/music/ambient'
abbr -a -- cdmd 'cd ~/music/drum-and-bass'
abbr -a -- cdmh 'cd ~/music/hardcore'
abbr -a -- cdmi 'cd ~/music/indie'
abbr -a -- cdmp 'cd ~/music/progressive'
abbr -a -- cdmr 'cd ~/music/rap'
abbr -a -- cdms 'cd ~/music/synth-pop'
abbr -a -- cdmt 'cd ~/music/techno'
abbr -a -- cdpd 'cd ~/podcasts'
abbr -a -- cds 'cd ~/screenshots'
abbr -a -- cdtr 'cd ~/code/tms-react'
abbr -a -- cdv 'cd ~/video'
abbr -a -- codei 'code --install-extension'
abbr -a -- codeu 'code --uninstall-extension'
abbr -a -- dctl 'sudo dinitctl'
abbr -a -- dw 'curl -LO'
abbr -a -- ga 'git add'
abbr -a -- gc 'git ci -m'
abbr -a -- gd 'git diff'
abbr -a -- gds 'git diff --staged'
abbr -a -- gs 'git status'
abbr -a -- his 'history -p'
abbr -a -- hisdel 'history delete -p'
abbr -a -- pacc 'sudo pacman -Sc --noconfirm'
abbr -a -- pacd 'sudo pacman -Sw --noconfirm --cachedir .'
abbr -a -- pacf 'pacman -Fx'
abbr -a -- paci 'sudo pacman -S'
abbr -a -- pacp 'sudo pacman -U'
abbr -a -- pacr 'sudo pacman -Rnsc'
abbr -a -- pacu 'sudo pacman -Syu --noconfirm'
abbr -a -- rmr 'rm -rf'
abbr -a -- ydl yt-dlp
abbr -a -- ydls 'yt-dlp --write-auto-sub --sub-lang=en'
