alias books 'nvim ~/notes/books.md'
alias confc 'nvim ~/.config/code/User/settings.json'
alias conff 'nvim ~/.config/fish/config.fish'
alias conffo 'nvim ~/.config/foot/foot.ini'
alias confs 'nvim ~/.config/sway/config'
alias confv 'nvim ~/.config/nvim/init.lua'
alias confw 'nvim ~/.config/waybar/config'
alias ip 'ip -c=auto'
alias notes 'nvim ~/notes/notes.md'
alias quotes 'nvim ~/notes/quotes.txt'
alias serials 'nvim ~/notes/serials.txt'
alias tokens 'nvim ~/notes/tokens.txt'
alias vocabulary 'nvim ~/notes/vocabulary.md'
alias vpn 'sudo /usr/local/bin/vpn'
alias work 'sudo /usr/local/bin/work'
alias rcp 'command rsync -ah --info=progress2'
alias poweroff 'loginctl poweroff'
alias reboot 'loginctl reboot'
