set dir $HOME/.config/JetBrains/jetbra/vmoptions
setenv IDEA_VM_OPTIONS $dir/idea.vmoptions
setenv CLION_VM_OPTIONS $dir/clion.vmoptions
setenv PHPSTORM_VM_OPTIONS $dir/phpstorm.vmoptions
setenv GOLAND_VM_OPTIONS $dir/goland.vmoptions
setenv PYCHARM_VM_OPTIONS $dir/pycharm.vmoptions
setenv WEBSTORM_VM_OPTIONS $dir/webstorm.vmoptions
setenv WEBIDE_VM_OPTIONS $dir/webide.vmoptions
setenv RIDER_VM_OPTIONS $dir/rider.vmoptions
setenv DATAGRIP_VM_OPTIONS $dir/datagrip.vmoptions
setenv RUBYMINE_VM_OPTIONS $dir/rubymine.vmoptions
setenv DATASPELL_VM_OPTIONS $dir/dataspell.vmoptions
setenv AQUA_VM_OPTIONS $dir/aqua.vmoptions
setenv RUSTROVER_VM_OPTIONS $dir/rustrover.vmoptions
setenv GATEWAY_VM_OPTIONS $dir/gateway.vmoptions
setenv JETBRAINS_CLIENT_VM_OPTIONS $dir/jetbrains_client.vmoptions
setenv JETBRAINSCLIENT_VM_OPTIONS $dir/jetbrainsclient.vmoptions
setenv STUDIO_VM_OPTIONS $dir/studio.vmoptions
setenv DEVECOSTUDIO_VM_OPTIONS $dir/devecostudio.vmoptions
