return {
  {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    build = function()
      require('nvim-treesitter.install').update({ with_sync = true })()
    end,
    config = function()
      local filetypes = {
        'angular',
        'awk',
        'bash',
        'c',
        'cmake',
        'cpp',
        'css',
        'csv',
        'desktop',
        'diff',
        'dockerfile',
        'editorconfig',
        'elixir',
        'fish',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'go',
        'gpg',
        'graphql',
        'html',
        'ini',
        'java',
        'javadoc',
        'javascript',
        'jinja',
        'jinja_inline',
        'jq',
        'jsdoc',
        'json',
        'just',
        'lua',
        'luadoc',
        'make',
        'markdown',
        'markdown_inline',
        'nginx',
        'powershell',
        'printf',
        'properties',
        'python',
        'regex',
        'requirements',
        'rust',
        'sql',
        'ssh_config',
        'strace',
        'sway',
        'tmux',
        'toml',
        'tsx',
        'typescript',
        'udev',
        'vim',
        'vimdoc',
        'vue',
        'xml',
        'yaml',
        'zig',
      }
      require('nvim-treesitter').install(filetypes)
      vim.api.nvim_create_autocmd('FileType', {
        pattern = vim.list_extend(filetypes, { 'typescriptreact' }),
        callback = function()
          vim.treesitter.start()
        end,
      })
    end,
  },
  {
    'nvim-treesitter/nvim-treesitter-textobjects',
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
  },
}
