return {
  {
    'nvim-treesitter/nvim-treesitter',
    build = function()
      require('nvim-treesitter.install').update({ with_sync = true })()
    end,
    config = function()
      local configs = require('nvim-treesitter.configs')
      configs.setup({
        ensure_installed = {
          'angular',
          'awk',
          'bash',
          'cmake',
          'css',
          'csv',
          'diff',
          'dockerfile',
          'editorconfig',
          'fish',
          'git_config',
          'git_rebase',
          'gitattributes',
          'gitcommit',
          'gitignore',
          'go',
          'gpg',
          'graphql',
          'html',
          'ini',
          'java',
          'javascript',
          'jinja',
          'jinja_inline',
          'jq',
          'jsdoc',
          'json',
          'jsonc',
          'just',
          'lua',
          'luadoc',
          'make',
          'markdown',
          'markdown_inline',
          'nginx',
          'properties',
          'python',
          'regex',
          'requirements',
          'rust',
          'sql',
          'ssh_config',
          'strace',
          'sway',
          'tmux',
          'toml',
          'tsx',
          'typescript',
          'udev',
          'vim',
          'vimdoc',
          'vue',
          'xml',
          'yaml',
        },
        sync_install = false,
        auto_install = true,
        highlight = {
          enable = true,
          -- Some languages depend on vim's regex highlighting system (such as Ruby) for indent rules.
          --  If you are experiencing weird indenting issues, add the language to
          --  the list of additional_vim_regex_highlighting and disabled languages for indent.
          additional_vim_regex_highlighting = { 'ruby' },
        },
        indent = { enable = true, disable = { 'ruby' } },
      })
    end,
  },
  {
    'nvim-treesitter/nvim-treesitter-textobjects',
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
  },
}
